<!DOCTYPE html>
<html>
<head>
	<title>Account</title>
</head>
<body>
	<h1>Account Information</h1>
	<label><a href="/logout">Log Out</a></label>
	<table>
		<tr>
			<td><label>First Name: </label></td>
			<td><label>{{firstname}}</label></td>
		</tr>
		<tr>
			<td><label>Last Name: </label></td>
			<td><label>{{lastname}}</label></td>
		</tr>
		<tr>
			<td><label>Email: </label></td>
			<td><label>{{email}}</label></td>
		</tr>
	</table>
</body>
</html>
